version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
  crypto-alert-service:
    build: ../apps/crypto-alert-service
    container_name: crypto-alert-service
    depends_on:
      - postgres
    restart: always
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "3000:3000"
    networks:
      - app_network
  worker:
    build: ../apps/worker
    container_name: worker
    depends_on:
      - postgres
    restart: always
    environment:
      NODE_ENV: production
      PG_DB_HOST: postgres
      PG_DB_USER: ${POSTGRES_USER}
      PG_DB_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DB_NAME: ${POSTGRES_DB}
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
